language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

install:
  - composer selfupdate
  - composer install --no-interaction --no-scripts --quiet

script: phpunit --verbose

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true